name: Firestore Access

on:
  push:
    branches:
      - main

jobs:
  firestore:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Google Cloud CLI
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}

      - name: Install Firebase CLI
        run: |
          # Install Firebase CLI tools
          curl -sL https://firebase.tools | bash
          firebase --version

      - name: Access Firestore
        run: |
          # Set Firebase project
          firebase use --add

          # Example Firestore access script (Node.js)
          echo "Accessing Firestore..."

          # Install dependencies (If needed)
          npm install

          # Run the script that accesses Firestore (e.g., firestore-access.js)
          node firestore-access.js
