name: Firestore Access

on:
  push:
    branches:
      - main

jobs:
  firestore:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Google Cloud CLI
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}

      - name: Access Firestore
        run: |
          # Install Firebase tools
          npm install -g firebase-tools

          # Authenticate with Firebase
          firebase login:ci --no-localhost --token "$(gcloud auth application-default print-access-token)"

          # Example Firestore access script (Node.js)
          echo "Firestore authenticated and ready!"
